<?php

/**
 * @file
 * Contains ead.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\file\Entity\File;

/**
 * Implements hook_help().
 */
function ead_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ead module.
    case 'help.page.ead':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Ingest and display EAD XML') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_entity_presave
 */

function ead_entity_presave(Drupal\Core\Entity\EntityInterface $entity) {
  $bundle = $entity->bundle();
  if ($bundle  == 'ead_finding_aid') {
    $fid = $entity->get('field_ead')->target_id;
    $file = File::load($fid);
    $xml = \simplexml_load_file($file->getFileUri());
    $title = (string) $xml->archdesc->did->unittitle[0];
    $entity->set('title', $title);

    $dates = [];
    foreach ($xml->archdesc->did->unitdate as $unitdate) {
      $tag = (string) $xml->archdesc->did->unitdate['encodinganalog'];
      $label = (string) $xml->archdesc->did->unitdate['label'];
      if ($tag == '245$f' ) {
        $dates[] = (string) trim($unitdate);
      }
      $ead_date = $entity->get('field_ead_date');
      foreach ($dates as $date){
        $ead_date->appendItem($date);
      }

    }

  }
}


/**
 * Implements hook_theme().
 */
function ead_theme() {
  return [
    'ead' => [
      'variables' => [
        'html' => '',
        'link' => '',
      ],
    ],
  ];
}
